version: '3.5'
services:
  api:
    container_name: devtest-api
    build: ./backend
  db:
    build: ./database
    container_name: devtest-db
    environment:
      MYSQL_ROOT_PASSWORD: root
  nginx:
    image: nginx:latest
    container_name: devtest-nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/html
